# Generated by Django 4.2.17 on 2024-12-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_contants_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contants',
            new_name='Contacts',
        ),
    ]
