# Generated by Django 4.2.17 on 2024-12-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_rename_contants_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='sen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
